name: weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  intl: ^0.20.1
  shared_preferences: ^2.3.5
  get_it: ^8.0.3
  freezed: ^2.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "logo/weather.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
flutter:
  uses-material-design: true
